# alternate multi-arch dockerfile for use with `balena push`
FROM node:16.17.0-alpine3.16

WORKDIR /usr/src/app

COPY *.json ./
COPY src/ src/

RUN npm ci --ignore-scripts && \
    npm run build && \
    npm prune --production && \
    npm cache clean --force

CMD [ "npm", "start" ]
